<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold leading-tight text-gray-800">Edit {{ $location->name }} content</h2></x-slot>
    <div class="py-12">
        <form method="POST" action="{{ route('seo.locations.content.update', $location) }}" class="mx-auto grid max-w-4xl gap-5 bg-white p-6 shadow-sm sm:rounded-lg md:grid-cols-2">@csrf @method('PATCH')
            <div><x-input-label for="status" value="Publication status" /><select id="status" name="status" class="mt-1 block w-full rounded-md border-gray-300" required><option value="draft" @selected(old('status', $location->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $location->status) === 'published')>Published</option></select><p class="mt-1 text-xs text-gray-500">Publishing requires every SEO field below.</p></div>
            <div class="md:col-span-2"><x-input-label for="heading" value="Public page heading" /><x-text-input id="heading" name="heading" maxlength="160" class="mt-1 block w-full" :value="old('heading', $location->content->heading ?? $location->name.' Escorts')" /><x-input-error :messages="$errors->get('heading')" class="mt-2" /></div>
            <div class="md:col-span-2"><x-input-label for="intro_content" value="Top introduction" /><textarea id="intro_content" name="intro_content" rows="6" class="mt-1 block w-full rounded-md border-gray-300">{{ old('intro_content', $location->content->intro_content) }}</textarea><x-input-error :messages="$errors->get('intro_content')" class="mt-2" /></div>
            <div class="md:col-span-2"><x-input-label for="bottom_content" value="Bottom SEO content (Markdown supported)" /><textarea id="bottom_content" name="bottom_content" rows="12" class="mt-1 block w-full rounded-md border-gray-300">{{ old('bottom_content', $location->content->bottom_content) }}</textarea><p class="mt-1 text-xs text-gray-500">Displayed after all listing sections and pagination, immediately before the footer.</p><x-input-error :messages="$errors->get('bottom_content')" class="mt-2" /></div>
            <div class="md:col-span-2"><x-input-label for="faq_content" value="FAQ content (optional)" /><textarea id="faq_content" name="faq_content" rows="5" class="mt-1 block w-full rounded-md border-gray-300">{{ old('faq_content', data_get($location->content->faq_content, 'content')) }}</textarea></div>
            <div><x-input-label for="seo_title" value="SEO title" /><x-text-input id="seo_title" name="seo_title" maxlength="70" class="mt-1 block w-full" :value="old('seo_title', $location->content->seo_title)" /><x-input-error :messages="$errors->get('seo_title')" class="mt-2" /></div>
            <div><x-input-label for="meta_description" value="Meta description" /><textarea id="meta_description" name="meta_description" maxlength="320" rows="3" class="mt-1 block w-full rounded-md border-gray-300">{{ old('meta_description', $location->content->meta_description) }}</textarea><x-input-error :messages="$errors->get('meta_description')" class="mt-2" /></div>
            <div class="md:col-span-2"><x-input-label for="canonical_path" value="Canonical path" /><x-text-input id="canonical_path" name="canonical_path" class="mt-1 block w-full" :value="old('canonical_path', $location->content->canonical_path)" /><x-input-error :messages="$errors->get('canonical_path')" class="mt-2" /></div>
            <div class="md:col-span-2 flex items-center justify-between"><a href="{{ route('seo.directory.index') }}" class="text-sm text-gray-600">Cancel</a><x-primary-button>Save location content</x-primary-button></div>
        </form>
    </div>
</x-app-layout>
