<x-app-layout>
    <x-slot name="header">
        <div><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Settings</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Mail delivery</h2></div>
    </x-slot>

    <div class="py-8 sm:py-10" x-data="{ mailer: {{ Js::from(old('mailer', $mailSettings->mailer)) }} }">
        <div class="mx-auto max-w-5xl space-y-6 px-4 sm:px-6 lg:px-8">
            @if (session('status'))<div class="flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 shadow-sm" role="status"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-emerald-600 text-white">✓</span>{{ session('status') }}</div>@endif
            @if ($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert"><p class="font-bold">Mail settings need attention.</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

            <form method="POST" action="{{ route('admin.settings.mail.update') }}" class="admin-card">@csrf @method('PATCH')
                <div class="admin-card-header bg-gradient-to-r from-indigo-50 via-white to-violet-50"><div class="flex gap-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M3 6.5 12 13l9-6.5M5 19h14a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2Z" stroke-width="2" stroke-linejoin="round"/></svg></span><div><h3 class="text-lg font-bold text-gray-900">Outgoing email</h3><p class="mt-1 max-w-2xl text-sm leading-6 text-gray-600">Configure account verification, password resets, provider updates, and urgent staff alerts without editing server files.</p></div></div></div>
                <div class="space-y-7 p-5 sm:p-6">
                    <fieldset><legend class="text-sm font-bold text-gray-900">Delivery method</legend><div class="mt-3 grid gap-3 sm:grid-cols-2">
                        <label class="cursor-pointer rounded-2xl border p-4 transition" :class="mailer === 'sendmail' ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100' : 'border-gray-200 hover:border-gray-300'"><span class="flex items-start gap-3"><input type="radio" name="mailer" value="sendmail" x-model="mailer" class="mt-1 border-gray-300 text-indigo-600"><span><strong class="block text-sm text-gray-900">Server mail (recommended for cPanel)</strong><span class="mt-1 block text-xs leading-5 text-gray-500">Uses the hosting account’s local Sendmail service. No username or password required.</span></span></span></label>
                        <label class="cursor-pointer rounded-2xl border p-4 transition" :class="mailer === 'smtp' ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100' : 'border-gray-200 hover:border-gray-300'"><span class="flex items-start gap-3"><input type="radio" name="mailer" value="smtp" x-model="mailer" class="mt-1 border-gray-300 text-indigo-600"><span><strong class="block text-sm text-gray-900">SMTP account</strong><span class="mt-1 block text-xs leading-5 text-gray-500">Connects to a cPanel mailbox or external transactional email provider.</span></span></span></label>
                    </div></fieldset>

                    <div class="grid gap-5 sm:grid-cols-2"><div><x-input-label for="from_address" value="From email address" /><input id="from_address" name="from_address" type="email" required value="{{ old('from_address', $mailSettings->from_address) }}" class="admin-field mt-2" placeholder="no-reply@example.com"></div><div><x-input-label for="from_name" value="Sender name" /><input id="from_name" name="from_name" required maxlength="120" value="{{ old('from_name', $mailSettings->from_name) }}" class="admin-field mt-2" placeholder="{{ config('app.name') }}"></div></div>

                    <div x-show="mailer === 'sendmail'" x-cloak class="rounded-2xl border border-gray-200 bg-gray-50 p-5"><x-input-label for="sendmail_path" value="Sendmail command" /><select id="sendmail_path" name="sendmail_path" class="admin-field mt-2 font-mono text-sm"><option value="/usr/sbin/sendmail -bs -i" @selected(old('sendmail_path', $mailSettings->sendmail_path) === '/usr/sbin/sendmail -bs -i')>/usr/sbin/sendmail (cPanel default)</option><option value="/usr/lib/sendmail -bs -i" @selected(old('sendmail_path', $mailSettings->sendmail_path) === '/usr/lib/sendmail -bs -i')>/usr/lib/sendmail</option></select><p class="mt-2 text-xs text-gray-500">Choose the location supported by your hosting provider. The cPanel default is selected automatically.</p></div>

                    <div x-show="mailer === 'smtp'" x-cloak class="rounded-2xl border border-gray-200 bg-gray-50 p-5"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><x-input-label for="smtp_host" value="SMTP server" /><input id="smtp_host" name="smtp_host" value="{{ old('smtp_host', $mailSettings->smtp_host) }}" class="admin-field mt-2" placeholder="mail.example.com"></div><div><x-input-label for="smtp_port" value="Port" /><input id="smtp_port" name="smtp_port" type="number" min="1" max="65535" value="{{ old('smtp_port', $mailSettings->smtp_port ?: 465) }}" class="admin-field mt-2"></div><div><x-input-label for="smtp_scheme" value="Connection security" /><select id="smtp_scheme" name="smtp_scheme" class="admin-field mt-2"><option value="smtp" @selected(old('smtp_scheme', $mailSettings->smtp_scheme) === 'smtp')>Automatic / STARTTLS</option><option value="smtps" @selected(old('smtp_scheme', $mailSettings->smtp_scheme) === 'smtps')>SSL/TLS</option></select></div><div><x-input-label for="smtp_username" value="Username" /><input id="smtp_username" name="smtp_username" autocomplete="username" value="{{ old('smtp_username', $mailSettings->smtp_username) }}" class="admin-field mt-2"></div><div><x-input-label for="smtp_password" value="Password" /><input id="smtp_password" name="smtp_password" type="password" autocomplete="new-password" class="admin-field mt-2" placeholder="{{ filled($mailSettings->smtp_password) ? 'Stored securely — leave blank to keep' : 'SMTP password' }}"><p class="mt-2 text-xs text-gray-500">Encrypted using the application key and never included in audit logs.</p></div></div></div>
                </div>
                <div class="flex justify-end border-t border-gray-100 bg-gray-50/60 px-5 py-4 sm:px-6"><x-primary-button class="!rounded-xl !bg-indigo-600 !px-6 !py-3 hover:!bg-indigo-700">Save mail settings</x-primary-button></div>
            </form>

            <section class="admin-card"><div class="admin-card-header"><h3 class="font-bold text-gray-900">Test delivery</h3><p class="mt-1 text-sm text-gray-600">Save your settings first, then send a real message to confirm it reaches an inbox.</p></div><form method="POST" action="{{ route('admin.settings.mail.test') }}" class="flex flex-col gap-3 p-5 sm:flex-row sm:items-end sm:p-6">@csrf<label class="min-w-0 flex-1"><span class="text-sm font-semibold text-gray-700">Recipient</span><input type="email" name="recipient" required value="{{ old('recipient', auth()->user()->email) }}" class="admin-field mt-2" placeholder="you@example.com"></label><button class="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-bold text-gray-700 shadow-sm transition hover:border-indigo-300 hover:text-indigo-700">Send test email</button></form></section>
        </div>
    </div>
</x-app-layout>
